site_name: Digital Anthropic Modules
repo_url: https://github.com/Digital-Anthropic
theme:
  name: material
  logo: assets/android-chrome-512x512.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: README.md
  - Terraform-Automation: Terraform_Github_Automation/README.md
  - AWS:
    - S3-CloudFront-Lambda: AWS_S3_CloudFront_Lambda/README.md

plugins:
  - social
  - search
